<a href="https://colab.research.google.com/github/ShivaniSinghRajawat/E-commerce-Product-Sales-Data-Analysis/blob/main/DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
!mkdir -p ~/.kaggle

In [10]:
!chmod 600 ~/.kaggle/kaggle.json

In [11]:
!pip install -q kaggle

In [16]:
!kaggle datasets download -d jmmvutu/summer-products-and-sales-in-ecommerce-wish
!unzip summer-products-and-sales-in-ecommerce-wish.zip

Dataset URL: https://www.kaggle.com/datasets/jmmvutu/summer-products-and-sales-in-ecommerce-wish
License(s): Attribution 4.0 International (CC BY 4.0)
summer-products-and-sales-in-ecommerce-wish.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  summer-products-and-sales-in-ecommerce-wish.zip
  inflating: computed_insight_success_of_active_sellers.csv
  inflating: summer-products-with-rating-and-performance_2020-08.csv
  inflating: unique-categories.csv
  inflating: unique-categories.sorted-by-count.csv

In [13]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [18]:
insights = pd.read_csv('/content/computed_insight_success_of_active_sellers.csv')
products = pd.read_csv('/content/summer-products-with-rating-and-performance_2020-08.csv')

In [19]:
insights.head(5)

,merchantid,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
0,5357bcf2bb72c5504882e889,2,120000,60000.0,4.219,320031.0,9.00,20.0,54.0,54.0,8836.0,1.0,50.0
1,5708773c3c02161b3f8c7900,5,107100,21420.0,3.934,139223.0,7.76,34.2,61.0,61.0,4010.0,3.0,60.0
2,5417aada4ad3ab27e954b76c,2,100007,50004.0,4.053,108048.0,8.00,8.0,-1.0,-1.0,5531.0,NaN,NaN
3,570f3a713a698c14278bb51e,1,100000,100000.0,3.889,19248.0,5.67,19.0,71.0,71.0,18393.0,1.0,100.0
4,53082ea15aefb07dfe1f2a4f,1,100000,100000.0,4.036,366898.0,5.00,33.0,85.0,85.0,13789.0,NaN,NaN

In [20]:
products.head(2)

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.0,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08

In [21]:
insights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   merchantid               958 non-null    object
 1   listedproducts           958 non-null    int64
 2   totalunitssold           958 non-null    int64
 3   meanunitssoldperproduct  958 non-null    float64
 4   rating                   958 non-null    float64
 5   merchantratingscount     958 non-null    float64
 6   meanproductprices        958 non-null    float64
 7   meanretailprices         958 non-null    float64
 8   averagediscount          958 non-null    float64
 9   meandiscount             958 non-null    float64
 10  meanproductratingscount  958 non-null    float64
 11  totalurgencycount        391 non-null    float64
 12  urgencytextrate          391 non-null    float64
dtypes: float64(10), int64(2), object(1)
memory usage: 97.4+ KB

In [22]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   object
 1   title_orig                    1573 non-null   object
 2   price                         1573 non-null   float64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   object
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1528 non-null   float64
 10  rating_four_count             1528 non-null   float64
 11  rating_three_count            1528 non-null   float64
 12  rating_two_count              1528 non-null   float64
 13  rating_one_count              1528 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   object
 19  product_color                 1532 non-null   object
 20  product_variation_size_id     1559 non-null   object
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   object
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            473 non-null    float64
 28  urgency_text                  473 non-null    object
 29  origin_country                1556 non-null   object
 30  merchant_title                1573 non-null   object
 31  merchant_name                 1569 non-null   object
 32  merchant_info_subtitle        1572 non-null   object
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   object
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      226 non-null    object
 38  product_url                   1573 non-null   object
 39  product_picture               1573 non-null   object
 40  product_id                    1573 non-null   object
 41  theme                         1573 non-null   object
 42  crawl_month                   1573 non-null   object
dtypes: float64(9), int64(15), object(19)
memory usage: 528.6+ KB

In [24]:
insights.columns = ['merchant_id', 'listed_products', 'total_units_sold',
       'mean_units_sold_per_product', 'rating', 'merchant_ratings_count',
       'mean_product_prices', 'mean_retail_prices', 'average_discount',
       'mean_discount', 'mean_product_ratings_count', 'total_urgency_count',
       'urgency_text_rate']

In [25]:
insights['total_urgency_count'].value_counts()

total_urgency_count
1.0    331
2.0     46
3.0      9
4.0      3
6.0      1
5.0      1
Name: count, dtype: int64

In [26]:
insights[['total_urgency_count', 'urgency_text_rate']] = insights[['total_urgency_count', 'urgency_text_rate']].fillna(value=0)

In [27]:
insights.duplicated().sum()

np.int64(0)

In [28]:
insights[insights['average_discount'] ==	insights['mean_discount']]['merchant_id'].count()

np.int64(834)

In [29]:
insights[insights['average_discount'] !=	insights['mean_discount']][['average_discount','mean_discount']].head(5)

    average_discount  mean_discount
6               -4.0          -3.86
8               33.0          33.33
9               -7.0          -6.80
11              87.0          87.25
12              -4.0          -4.17

In [30]:
insights.drop('mean_discount', axis=1, inplace=True)

In [31]:
products[products['rating_five_count'].isna()].head(2)

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
74,Fashion Women Sleeveless Lace Vest Loose V Nec...,Fashion Women Sleeveless Lace Vest Loose V Nec...,8.0,33,EUR,10,0,5.0,0,NaN,...,1496,4.169786,592955ef980a346d826f7bfc,0,NaN,https://www.wish.com/c/5ed0dfc51fa8446451b19c0d,https://contestimg.wish.com/api/webimage/5ed0d...,5ed0dfc51fa8446451b19c0d,summer,2020-08
112,Womens Summer Fashion Lip Print 2pc Set Ladies...,Womens Summer Fashion Lip Print 2pc Set Ladies...,5.0,51,EUR,10,0,5.0,0,NaN,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5eb90ab5ad67f63678d15ed9,https://contestimg.wish.com/api/webimage/5eb90...,5eb90ab5ad67f63678d15ed9,summer,2020-08

In [32]:
products[['rating_five_count','rating_four_count',
          'rating_three_count',	'rating_two_count',
          'rating_one_count']] = products[['rating_five_count','rating_four_count',
                                           'rating_three_count',	'rating_two_count',
                                           'rating_one_count']].fillna(value=0)

In [33]:
products['product_color'].value_counts()

product_color
black         302
white         254
yellow        105
pink           99
blue           99
             ...
violet          1
blackwhite      1
darkgreen       1
rosegold        1
gold            1
Name: count, Length: 101, dtype: int64

In [34]:
products['product_color'].fillna(value='undefind', inplace=True)

<ipython-input-34-242a6d4bb12f>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products['product_color'].fillna(value='undefind', inplace=True)

In [35]:
products['product_variation_size_id'].value_counts()

product_variation_size_id
S            641
XS           356
M            200
XXS          100
L             49
            ...
5              1
1 PC - XL      1
H01            1
40 cm          1
SIZE S         1
Name: count, Length: 106, dtype: int64

In [36]:
products['product_variation_size_id'].fillna(value='undefind', inplace=True)

<ipython-input-36-0f3c86d8dba7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products['product_variation_size_id'].fillna(value='undefind', inplace=True)

In [37]:
products['has_urgency_banner'].value_counts()

has_urgency_banner
1.0    473
Name: count, dtype: int64

In [38]:
products['has_urgency_banner'].fillna(value=0, inplace=True)
products['urgency_text'].fillna(value='No Banner', inplace=True)

<ipython-input-38-0b8b4cb262d0>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products['has_urgency_banner'].fillna(value=0, inplace=True)
<ipython-input-38-0b8b4cb262d0>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products['urgency_text'].fillna(value='No Banner', inplace=True)

In [39]:
products['origin_country'].fillna(value='Undifind', inplace=True)

<ipython-input-39-b706b43841ce>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products['origin_country'].fillna(value='Undifind', inplace=True)

In [40]:
products[products['merchant_name'].isna()].head()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
408,Plus la taille des femmes de la mode lâche déc...,Plus Size Women's Fashion Loose Casual sleevel...,5.83,5,EUR,100,0,4.36,22,13.0,...,17471,3.952836,5aab3c8ea6bf7a704caec65c,0,NaN,https://www.wish.com/c/5e9932cab3eafb25c00ba79f,https://contestimg.wish.com/api/webimage/5e993...,5e9932cab3eafb25c00ba79f,summer,2020-08
505,Plus la taille des femmes de la mode lâche déc...,Plus Size Women's Fashion Loose Casual sleevel...,5.83,5,EUR,100,0,4.36,22,13.0,...,17471,3.952836,5aab3c8ea6bf7a704caec65c,0,NaN,https://www.wish.com/c/5e9932cab3eafb25c00ba79f,https://contestimg.wish.com/api/webimage/5e993...,5e9932cab3eafb25c00ba79f,summer,2020-08
1103,Plus la taille des femmes de la mode lâche déc...,Plus Size Women's Fashion Loose Casual sleevel...,5.83,5,EUR,100,0,4.36,22,13.0,...,17471,3.952836,5aab3c8ea6bf7a704caec65c,0,NaN,https://www.wish.com/c/5e9932cab3eafb25c00ba79f,https://contestimg.wish.com/api/webimage/5e993...,5e9932cab3eafb25c00ba79f,summer,2020-08
1350,Mode pour dames Pantalon imprimé Femmes Pantal...,Women Fashion Loose Casual Printed Women Trous...,12.00,11,EUR,1000,0,3.70,647,271.0,...,17471,3.952836,5aab3c8ea6bf7a704caec65c,0,NaN,https://www.wish.com/c/5c8600ae1cb98f7a3a7099c2,https://contestimg.wish.com/api/webimage/5c860...,5c8600ae1cb98f7a3a7099c2,summer,2020-08

In [41]:
# Replace values in 'merchant_name' where 'merchant_title' is 'DERNMUUR'
products.loc[products['merchant_title'] == 'DERNMUUR', 'merchant_name'] = products['merchant_title']

In [42]:
products['merchant_info_subtitle'].fillna(value='Undifind', inplace=True)

<ipython-input-42-86e45528ea8a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products['merchant_info_subtitle'].fillna(value='Undifind', inplace=True)

In [43]:
products.drop(['merchant_profile_picture'], axis=1, inplace=True)

In [44]:
products.duplicated().sum()

np.int64(34)

In [45]:
products.drop_duplicates(inplace=True)
print(products.duplicated().sum())

0

In [46]:
products['crawl_month'].value_counts()

crawl_month
2020-08    1539
Name: count, dtype: int64

In [47]:
products.drop(['crawl_month'], axis=1, inplace=True)

In [48]:
products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1539 entries, 0 to 1572
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1539 non-null   object
 1   title_orig                    1539 non-null   object
 2   price                         1539 non-null   float64
 3   retail_price                  1539 non-null   int64
 4   currency_buyer                1539 non-null   object
 5   units_sold                    1539 non-null   int64
 6   uses_ad_boosts                1539 non-null   int64
 7   rating                        1539 non-null   float64
 8   rating_count                  1539 non-null   int64
 9   rating_five_count             1539 non-null   float64
 10  rating_four_count             1539 non-null   float64
 11  rating_three_count            1539 non-null   float64
 12  rating_two_count              1539 non-null   float64
 13  rating_one_count              1539 non-null   float64
 14  badges_count                  1539 non-null   int64
 15  badge_local_product           1539 non-null   int64
 16  badge_product_quality         1539 non-null   int64
 17  badge_fast_shipping           1539 non-null   int64
 18  tags                          1539 non-null   object
 19  product_color                 1539 non-null   object
 20  product_variation_size_id     1539 non-null   object
 21  product_variation_inventory   1539 non-null   int64
 22  shipping_option_name          1539 non-null   object
 23  shipping_option_price         1539 non-null   int64
 24  shipping_is_express           1539 non-null   int64
 25  countries_shipped_to          1539 non-null   int64
 26  inventory_total               1539 non-null   int64
 27  has_urgency_banner            1539 non-null   float64
 28  urgency_text                  1539 non-null   object
 29  origin_country                1539 non-null   object
 30  merchant_title                1539 non-null   object
 31  merchant_name                 1539 non-null   object
 32  merchant_info_subtitle        1539 non-null   object
 33  merchant_rating_count         1539 non-null   int64
 34  merchant_rating               1539 non-null   float64
 35  merchant_id                   1539 non-null   object
 36  merchant_has_profile_picture  1539 non-null   int64
 37  product_url                   1539 non-null   object
 38  product_picture               1539 non-null   object
 39  product_id                    1539 non-null   object
 40  theme                         1539 non-null   object
dtypes: float64(9), int64(15), object(17)
memory usage: 505.0+ KB

In [49]:
insights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   merchant_id                  958 non-null    object
 1   listed_products              958 non-null    int64
 2   total_units_sold             958 non-null    int64
 3   mean_units_sold_per_product  958 non-null    float64
 4   rating                       958 non-null    float64
 5   merchant_ratings_count       958 non-null    float64
 6   mean_product_prices          958 non-null    float64
 7   mean_retail_prices           958 non-null    float64
 8   average_discount             958 non-null    float64
 9   mean_product_ratings_count   958 non-null    float64
 10  total_urgency_count          958 non-null    float64
 11  urgency_text_rate            958 non-null    float64
dtypes: float64(9), int64(2), object(1)
memory usage: 89.9+ KB